version: '3'

services:
  redis:
    restart: always
    image: redis:7-alpine
    environment:
      TZ: Asia/Shanghai
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

  spider:
    restart: always
    image: njnu-classroom.io/njnu-classroom-spider:production
    command: [ "java", "-Xms256m", "-Xmx512m", "-jar", "/server.jar", "--spring.cloud.nacos.server-addr=10.144.0.252:8848", "--spring.profiles.active=prd" ]
    volumes:
      - /opt/njnu-classroom/logs/njnu-classroom-spider:/logs
    depends_on:
      - redis
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 1024M
  portal:
    restart: always
    image: njnu-classroom.io/njnu-classroom-portal:production
    command: [ "java", "-Xms256m", "-Xmx256m", "-jar", "/server.jar", "--spring.cloud.nacos.server-addr=10.144.0.252:8848", "--spring.profiles.active=prd" ]
    volumes:
      - /opt/njnu-classroom/logs/njnu-classroom-portal:/logs
    depends_on:
      - redis
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 512M
  core:
    restart: always
    image: njnu-classroom.io/njnu-classroom-core:production
    command: [ "java", "-Xms256m", "-Xmx512m", "-jar", "/server.jar", "--spring.cloud.nacos.server-addr=10.144.0.252:8848", "--spring.profiles.active=prd" ]
    volumes:
      - /opt/njnu-classroom/logs/njnu-classroom-core:/logs
    depends_on:
      - redis
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 1024M
  explore:
    restart: always
    image: njnu-classroom.io/njnu-classroom-explore:production
    command: [ "java", "-Xms256m", "-Xmx256m", "-jar", "/server.jar", "--spring.cloud.nacos.server-addr=10.144.0.252:8848", "--spring.profiles.active=prd" ]
    volumes:
      - /opt/njnu-classroom/logs/njnu-classroom-explore:/logs
    depends_on:
      - redis
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 512M
  gateway:
    restart: always
    image: njnu-classroom.io/njnu-classroom-gateway:production
    command: [ "java", "-Xms256m", "-Xmx256m", "-jar", "/server.jar", "--spring.cloud.nacos.server-addr=10.144.0.252:8848", "--spring.profiles.active=prd" ]
    environment:
      TZ: Asia/Shanghai
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 512M
