version: '3'

services:
  redis:
    restart: always
    image: redis:7-alpine
    environment:
      TZ: Asia/Shanghai
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  spider:
    restart: always
    image: njnu-classroom.io/njnu-classroom-spider:production
    command: ["java", "-Xms256m", "-Xmx256m", "-jar", "/server.jar", "--spring.profiles.active=prd"]
    volumes:
    - /opt/njnu-classroom/logs/njnu-classroom-spider:/logs
    depends_on:
    - redis
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 512M
  portal:
    restart: always
    image: njnu-classroom.io/njnu-classroom-portal:production
    command: ["java", "-Xms256m", "-Xmx256m", "-jar", "/server.jar", "--spring.profiles.active=prd"]
    volumes:
    - /opt/njnu-classroom/logs/njnu-classroom-portal:/logs
    depends_on:
    - redis
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 512M
  core:
    restart: always
    image: njnu-classroom.io/njnu-classroom-core:production
    command: ["java", "-Xms256m", "-Xmx256m", "-jar", "/server.jar", "--spring.profiles.active=prd"]
    volumes:
    - /opt/njnu-classroom/logs/njnu-classroom-core:/logs
    depends_on:
    - redis
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 512M
  explore:
    restart: always
    image: njnu-classroom.io/njnu-classroom-explore:production
    command: ["java", "-Xms256m", "-Xmx256m", "-jar", "/server.jar", "--spring.profiles.active=prd"]
    volumes:
    - /opt/njnu-classroom/logs/njnu-classroom-explore:/logs
    depends_on:
    - redis
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 512M

  nginx:
    restart: always
    image: njnu-classroom.io/njnu-classroom-nginx:latest
    depends_on: ["spider", "portal", "core", "explore"]
    environment:
      TZ: Asia/Shanghai
    ports:
    - 8080:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:443"]
