version: '3'

services:
  spider_dev:
    image: njnu-classroom.io/njnu-classroom-spider:develop
    build: /opt/njnu-classroom-server.git/njnu-classroom-spider
  portal_dev:
    image: njnu-classroom.io/njnu-classroom-portal:develop
    build: /opt/njnu-classroom-server.git/njnu-classroom-portal
  core_dev:
    image: njnu-classroom.io/njnu-classroom-core:develop
    build: /opt/njnu-classroom-server.git/njnu-classroom-core
  explore_dev:
    image: njnu-classroom.io/njnu-classroom-explore:develop
    build: /opt/njnu-classroom-server.git/njnu-classroom-explore
  gateway_dev:
    image: njnu-classroom.io/njnu-classroom-gateway:develop
    build: /opt/njnu-classroom-server.git/njnu-classroom-gateway

  spider_prd:
    image: njnu-classroom.io/njnu-classroom-spider:production
    build: /opt/njnu-classroom-server.git/njnu-classroom-spider
  portal_prd:
    image: njnu-classroom.io/njnu-classroom-portal:production
    build: /opt/njnu-classroom-server.git/njnu-classroom-portal
  core_prd:
    image: njnu-classroom.io/njnu-classroom-core:production
    build: /opt/njnu-classroom-server.git/njnu-classroom-core
  explore_prd:
    image: njnu-classroom.io/njnu-classroom-explore:production
    build: /opt/njnu-classroom-server.git/njnu-classroom-explore
  gateway_prd:
    image: njnu-classroom.io/njnu-classroom-gateway:production
    build: /opt/njnu-classroom-server.git/njnu-classroom-gateway
