spring:
  application:
    name: njnu-classroom-explore
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/njnu_classroom
    username: njnu_classroom
    password: njnu-000
    hikari:
      maximum-pool-size: 100
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  cache:
    type: redis

redis:
  prefix: explore
  key:
    grids: grids
  expire:
    grids: 7d
