spring:
  datasource:
    url: jdbc:mariadb://10.144.0.252:3306/njnu_classroom
    username: njnu_classroom
    password: ''
  data:
    redis:
      host: 10.144.0.252
      port: 6379
      database: 6
  mail:
    host: smtp.repigeons.cn
    username: njnu-classroom@repigeons.cn
    receivers: ''

jwt:
  secret: 'njnu-000'
