server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  cloud:
    loadbalancer:
      cache:
        enabled: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
  data:
    redis:
      connect-timeout: 1s
      lettuce:
        pool:
          min-idle: 3
  cache:
    type: redis

redis:
  prefix: explore
  key:
    grids: 'grids'
    shuttle-stations-position: 'static::position::stations'
    shuttle-route: 'shuttle::routes'
  expire:
    grids: 7d
    shuttle-stations-position: 7d
    shuttle-route: 3d

logging:
  level:
    root: info
    cn.repigeons: debug
    cn.repigeons.njnu.classroom.mbg: info
