server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  webflux:
    base-path: /core
  cloud:
    loadbalancer:
      cache:
        enabled: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
  data:
    redis:
      connect-timeout: 1s
      lettuce:
        pool:
          min-idle: 3
  cache:
    type: redis
    redis:
      key-prefix: core
      key:
        classrooms: 'static::classrooms'
        buildings-position: 'static::position::buildings'
      expire:
        classrooms: 7d
        buildings-position: 7d

logging:
  level:
    root: info
    cn.repigeons: debug
    cn.repigeons.njnu.classroom.mybatis: info
