spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/njnu_classroom
    username: njnu_classroom
    password: njnu-000
    hikari:
      maximum-pool-size: 100
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  mail:
    host: smtp.repigeons.cn
    port: 465
    username: ''
    password: ''

redis:
  prefix: core
  key:
    classrooms: 'static:classrooms'
    buildings-position: 'static:position:buildings'
  expire:
    classrooms: 3d
    buildings-position: 3d

account:
  username: ''
  password: ''
  gid: ''
