spring:
  application:
    name: njnu-classroom-portal
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/njnu_classroom
    username: njnu_classroom
    password: njnu-000
    hikari:
      maximum-pool-size: 100
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  cache:
    type: redis

redis:
  prefix: portal
  key:
    notice: notice
#  expire:

jwt:
  expire: 3600
  secret: ''

mp:
  appid: wx42f3e578c5411a23
  secret: ''
