server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  cloud:
    loadbalancer:
      cache:
        enabled: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
  data:
    redis:
      connect-timeout: 1s
      lettuce:
        pool:
          min-idle: 3
  cache:
    type: redis

redis:
  prefix: portal
  key:
    notice: notice

jwt:
  expire: 3600

mp:
  appid: wx42f3e578c5411a23

logging:
  level:
    root: info
    cn.repigeons: debug
    cn.repigeons.njnu.classroom.mbg: info
