server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  application:
    name: njnu-classroom-gateway
  cloud:
    loadbalancer:
      cache:
        enabled: false
    nacos:
      server-addr: 10.144.0.252:8848
      discovery:
        namespace: njnu-classroom
        group: ${spring.profiles.active}
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5000
      routes:
        - id: spider
          uri: lb://njnu-classroom-spider
          predicates:
            - Path=/spider/**
          filters:
            - StripPrefix=1
        - id: portal
          uri: lb://njnu-classroom-portal
          predicates:
            - Path=/portal/**
          filters:
            - StripPrefix=1
        - id: core
          uri: lb://njnu-classroom-core
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
        - id: explore
          uri: lb://njnu-classroom-explore
          predicates:
            - Path=/explore/**
          filters:
            - StripPrefix=1

knife4j:
  gateway:
    enabled: true
    routes:
      - name: spider
        service-name: njnu-classroom-spider
        context-path: /spider
        url: /spider/v3/api-docs
      - name: portal
        service-name: njnu-classroom-portal
        context-path: /portal
        url: /portal/v3/api-docs
      - name: core
        service-name: njnu-classroom-core
        context-path: /core
        url: /core/v3/api-docs
      - name: explore
        service-name: njnu-classroom-explore
        context-path: /explore
        url: /explore/v3/api-docs
