server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  application:
    name: njnu-classroom-gateway
  cloud:
    loadbalancer:
      cache:
        enabled: false
    nacos:
      server-addr: 10.144.0.252:8848
      discovery:
        namespace: njnu-classroom
        group: ${spring.profiles.active}
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5000
      routes:
        - id: spider
          uri: lb://njnu-classroom-spider
          predicates:
            - Path=/spider/**
          filters:
            - StripPrefix=1
        - id: portal
          uri: lb://njnu-classroom-portal
          predicates:
            - Path=/portal/**
          filters:
            - StripPrefix=1
        - id: core
          uri: lb://njnu-classroom-core
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
        - id: explore
          uri: lb://njnu-classroom-explore
          predicates:
            - Path=/explore/**
          filters:
            - StripPrefix=1
