spring:
  datasource:
    url: jdbc:mariadb://10.144.0.252:3306/njnu_classroom
    username: njnu_classroom
    password: ''
  data:
    redis:
      host: 10.144.0.252
      port: 6379
      database: 6

account:
  username: ''
  password: ''
  gid: ''

proxy-pool: # https://github.com/jhao104/proxy_pool.git
  all: 'http://demo.spiderpy.cn/all'
