server:
  shutdown: graceful

spring:
  application:
    name: njnu-classroom-spider
  lifecycle:
    timeout-per-shutdown-phase: 10s
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
  data:
    redis:
      connect-timeout: 1s
      lettuce:
        pool:
          min-idle: 1
  cache:
    type: redis
  mail:
    host: smtp.repigeons.cn
    port: 465
    username: njnu-classroom@repigeons.cn
    # password:

redis:
  prefix: spider
  key:
    cookies: 'cookies'
    time-info: 'time:info'
    jxl-info: 'classroom:jxl'
    classroom-info: 'classroom:info'
  expire:
    cookies: 30m
    time-info: 3d
    jxl-info: 3d
    classroom-info: 3d

account:
  username: ''
  password: ''
  gid: ''


logging:
  level:
    root: info
    cn.repigeons: debug
    cn.repigeons.njnu.classroom.mbg: info
