server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  webflux:
    base-path: /spider
  cloud:
    loadbalancer:
      cache:
        enabled: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
  data:
    redis:
      connect-timeout: 1s
      lettuce:
        pool:
          min-idle: 3
  cache:
    type: redis

redis:
  prefix: spider
  key:
    cookies: 'cookies'
    time-info: 'time::info'
    jxl-info: 'classroom::jxl'
    classroom-info: 'classroom::info'
  expire:
    cookies: 30m
    time-info: 3d
    jxl-info: 3d
    classroom-info: 3d

logging:
  level:
    root: info
    cn.repigeons: debug
    cn.repigeons.njnu.classroom.mbg: info
