spring:
  application:
    name: njnu-classroom-spider
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/njnu_classroom
    username: njnu_classroom
    password: njnu-000
    hikari:
      maximum-pool-size: 100
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  mail:
    host: smtp.repigeons.cn
    port: 465
    username: njnu-classroom@repigeons.cn
    # password:
  cache:
    type: redis

redis:
  prefix: spider
  key:
    cookies: cookies
    time-info: timeInfo
    jxl-info: jxlInfo
  expire:
    cookies: 30m
    time-info: 3d
    jxl-info: 3d

account:
  username: ''
  password: ''
  gid: ''
